# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import sip
sip.setapi('QString', 2)

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 589)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(700, 500, 191, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 500, 121, 16))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 0, 71, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Angles_spinBox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_Angles_spinBox.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Angles_spinBox.setObjectName("verticalLayout_Angles_spinBox")
        self.doubleSpinBox_Min = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_Min.setMaximum(180.0)
        self.doubleSpinBox_Min.setProperty("value", 20.0)
        self.doubleSpinBox_Min.setObjectName("doubleSpinBox_Min")
        self.verticalLayout_Angles_spinBox.addWidget(self.doubleSpinBox_Min)
        self.doubleSpinBox_Max = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_Max.setMaximum(180.0)
        self.doubleSpinBox_Max.setProperty("value", 30.0)
        self.doubleSpinBox_Max.setObjectName("doubleSpinBox_Max")
        self.verticalLayout_Angles_spinBox.addWidget(self.doubleSpinBox_Max)
        self.doubleSpinBox_Delta = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_Delta.setDecimals(3)
        self.doubleSpinBox_Delta.setMinimum(0.0)
        self.doubleSpinBox_Delta.setMaximum(5.0)
        self.doubleSpinBox_Delta.setSingleStep(0.01)
        self.doubleSpinBox_Delta.setProperty("value", 0.0)
        self.doubleSpinBox_Delta.setObjectName("doubleSpinBox_Delta")
        self.verticalLayout_Angles_spinBox.addWidget(self.doubleSpinBox_Delta)
        self.spinBox_Bins = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_Bins.setToolTip("")
        self.spinBox_Bins.setMinimum(10)
        self.spinBox_Bins.setMaximum(10000)
        self.spinBox_Bins.setProperty("value", 400)
        self.spinBox_Bins.setObjectName("spinBox_Bins")
        self.verticalLayout_Angles_spinBox.addWidget(self.spinBox_Bins)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 81, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Angles = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Angles.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_Angles.setContentsMargins(0, 4, 0, 8)
        self.verticalLayout_Angles.setSpacing(1)
        self.verticalLayout_Angles.setObjectName("verticalLayout_Angles")
        self.label_angleMin = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_angleMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_angleMin.setObjectName("label_angleMin")
        self.verticalLayout_Angles.addWidget(self.label_angleMin)
        self.label_angleMax = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_angleMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_angleMax.setObjectName("label_angleMax")
        self.verticalLayout_Angles.addWidget(self.label_angleMax)
        self.label_angleDelta = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_angleDelta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_angleDelta.setObjectName("label_angleDelta")
        self.verticalLayout_Angles.addWidget(self.label_angleDelta)
        self.label_bins = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_bins.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bins.setObjectName("label_bins")
        self.verticalLayout_Angles.addWidget(self.label_bins)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 341, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_AnglesDisp = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_AnglesDisp.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_AnglesDisp.setObjectName("horizontalLayout_AnglesDisp")
        self.label_CTemp1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_CTemp1.setFont(font)
        self.label_CTemp1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CTemp1.setObjectName("label_CTemp1")
        self.horizontalLayout_AnglesDisp.addWidget(self.label_CTemp1)
        self.lcdNumber_CTemp1 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcdNumber_CTemp1.setFont(font)
        self.lcdNumber_CTemp1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_CTemp1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_CTemp1.setProperty("value", 22.01)
        self.lcdNumber_CTemp1.setObjectName("lcdNumber_CTemp1")
        self.horizontalLayout_AnglesDisp.addWidget(self.lcdNumber_CTemp1)
        self.label_CTemp2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_CTemp2.setFont(font)
        self.label_CTemp2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_CTemp2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CTemp2.setObjectName("label_CTemp2")
        self.horizontalLayout_AnglesDisp.addWidget(self.label_CTemp2)
        self.lcdNumber_CTemp2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber_CTemp2.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_CTemp2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_CTemp2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_CTemp2.setProperty("value", 22.45)
        self.lcdNumber_CTemp2.setObjectName("lcdNumber_CTemp2")
        self.horizontalLayout_AnglesDisp.addWidget(self.lcdNumber_CTemp2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setChecked(False)
        self.actionNew.setEnabled(True)
        self.actionNew.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionNew.setObjectName("actionNew")
        self.actionDisk_Path = QtWidgets.QAction(MainWindow)
        self.actionDisk_Path.setObjectName("actionDisk_Path")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionContacts = QtWidgets.QAction(MainWindow)
        self.actionContacts.setObjectName("actionContacts")
        self.actionAcquire = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/res/movie-player-play-button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcquire.setIcon(icon)
        self.actionAcquire.setObjectName("actionAcquire")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/res/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon1)
        self.actionStop.setObjectName("actionStop")
        self.actionCancel = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/res/cancel-button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancel.setIcon(icon2)
        self.actionCancel.setObjectName("actionCancel")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/res/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon3)
        self.actionPause.setObjectName("actionPause")
        self.actionRestart = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/res/replay.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestart.setIcon(icon4)
        self.actionRestart.setObjectName("actionRestart")
        self.actionLicenses = QtWidgets.QAction(MainWindow)
        self.actionLicenses.setObjectName("actionLicenses")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionDisk_Path)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionContacts)
        self.menuHelp.addAction(self.actionLicenses)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionAcquire)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionRestart)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionCancel)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DCScan"))
        self.label.setText(_translate("MainWindow", "Acquisition Progress"))
        self.label_angleMin.setText(_translate("MainWindow", "Angle min"))
        self.label_angleMax.setText(_translate("MainWindow", "Angle max"))
        self.label_angleDelta.setText(_translate("MainWindow", "Angle delta"))
        self.label_bins.setText(_translate("MainWindow", "# Bins"))
        self.label_CTemp1.setText(_translate("MainWindow", "Crystal 1 Temp"))
        self.label_CTemp2.setText(_translate("MainWindow", "Crystal 2 Temp"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "&Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionDisk_Path.setText(_translate("MainWindow", "Disk Path"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))
        self.actionContacts.setText(_translate("MainWindow", "Contacts"))
        self.actionAcquire.setText(_translate("MainWindow", "run"))
        self.actionAcquire.setToolTip(_translate("MainWindow", "<html><head/><body><p>Starts the data acquisition</p><p>Icon made by <a href=\"https://www.freepik.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">Freepik</span></a> from <a href=\"https://www.flaticon.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">www.flaticon.com</span></a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\"><span style=\" text-decoration: underline; color:#0000ff;\">CC 3.0 BY</span></a></p></body></html>"))
        self.actionStop.setText(_translate("MainWindow", "stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stops the data acquisition and saves data to file</p><p>Icon made by <a href=\"https://www.flaticon.com/authors/smashicons\"><span style=\" text-decoration: underline; color:#0000ff;\">Smashicons</span></a> from <a href=\"https://www.flaticon.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">www.flaticon.com</span></a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\"><span style=\" text-decoration: underline; color:#0000ff;\">CC 3.0 BY</span></a></p></body></html>"))
        self.actionCancel.setText(_translate("MainWindow", "cancel"))
        self.actionCancel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stops the data acquisition and discards all the data</p><p>Icon made by <a href=\"https://www.flaticon.com/authors/google\"><span style=\" text-decoration: underline; color:#0000ff;\">Google</span></a> from <a href=\"https://www.flaticon.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">www.flaticon.com</span></a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\"><span style=\" text-decoration: underline; color:#0000ff;\">CC 3.0 BY</span></a></p></body></html>"))
        self.actionPause.setText(_translate("MainWindow", "pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pauses the data acquisition</p><p>Icon made by <a href=\"https://www.flaticon.com/authors/smashicons\"><span style=\" text-decoration: underline; color:#0000ff;\">Smashicons</span></a> from <a href=\"https://www.flaticon.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">www.flaticon.com</span></a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\"><span style=\" text-decoration: underline; color:#0000ff;\">CC 3.0 BY</span></a></p></body></html>"))
        self.actionRestart.setText(_translate("MainWindow", "restart"))
        self.actionRestart.setToolTip(_translate("MainWindow", "<html><head/><body><p>Restarts the data acquisition, discarding current (if running)</p><div>Icon made by <a href=\"https://www.flaticon.com/authors/chanut\" title=\"Chanut\">Chanut</a> from <a href=\"https://www.flaticon.com/\"                 title=\"Flaticon\">www.flaticon.com</a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\"                 title=\"Creative Commons BY 3.0\" target=\"_blank\">CC 3.0 BY</a></div></body></html>"))
        self.actionLicenses.setText(_translate("MainWindow", "Licenses"))
			
			
class UpdateThread(QtCore.Qthread):
	received = QtCore.pyqtSignal([str], [unicode])
	
	def randomTemp1(self):
		self.lcdNumber_CTemp1.setProperty("value", np.random.randn(1))
	
	def run(self):
		while(True):
			self.received.emit('')
			
		
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
	
	t = UpdateThread()
	t.received.connect()
	
    MainWindow.show()
    sys.exit(app.exec_())

